### ISSUE TITLE
Support of the --watch flag

### ISSUE THREAD

**Issue by cardin** [meyfa/ts-node-test#28]
It would be great if the `--watch` flag is supported in ts-node-test as well: https://nodejs.org/docs/latest-v19.x/api/test.html#watch-mode

**Comment by meyfa** [comment]
Sure! That sounds nice. Would you like to send a pull request?

**Comment by meyfa** [comment]
Implemented support for `--watch` in PR #32 and released as v0.3.0 just now. Please report back if you encounter any issues using it.
